### PR TITLE
Add a Gibbs sampler for the regularized logistic regression

### LINKED ISSUE #11: Implement sampler for linear regularized regression
See section 2.1. in  [1].

[1] Makalic, Enes, and Daniel F. Schmidt. “High-Dimensional Bayesian Regularised Regression with the BayesReg Package.” ArXiv Preprint ArXiv:1611.06649, 2016.

### LINKED ISSUE #12: Implement sampler for logistic regularized regression
See section 2.2 in [1]. We should be able to reuse most of the negative binomial regularized regression's implementation.

[1] Makalic, Enes, and Daniel F. Schmidt. “High-Dimensional Bayesian Regularised Regression with the BayesReg Package.” ArXiv Preprint ArXiv:1611.06649, 2016.

### PR DESCRIPTION
**Pull request by rlouf**
This PR adds a Gibbs sampler for the regularized binary logistic regression, as presented in Makalik & Schmidt (2016). The change from the regularized negative binomial regression is trivial, and I opened this PR to start thinking about how modular the implementation needs to be.

Closes #12, and we should aim to close #11 as well.

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.  If your commit description starts with "Fix...", then you're probably making this mistake.
+ [x] There are tests covering the changes introduced in the PR.

### CODE REVIEW

**Review by brandonwillard — APPROVED** [review]
I'm fine with this refactoring.  Just don't be surprised if it's refactored again soon, because this project is likely to undergo large changes quickly.

**Comment by zoj613** [comment]
Is this ready for review or should I wait till its no longer in draft state? @rlouf

**Comment by rlouf** [comment]
@zoj613 Feel free to review while I pull the changes from `main`

**Comment by rlouf** [comment]
@zoj613 All checks pass now. Waiting for your review to merge.

**Review by brandonwillard — APPROVED** [review]

**Pull request merged**
